import { PDFDocument, StandardFonts, rgb, type PDFPage, type PDFFont } from "pdf-lib";

import type { getCustomerInvoiceDocument } from "./invoiceDocument";

type InvoiceDocument = NonNullable<
  Awaited<ReturnType<typeof getCustomerInvoiceDocument>>
>;

type Fonts = {
  regular: PDFFont;
  bold: PDFFont;
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 42;

function safeText(value: string | null | undefined) {
  return (value ?? "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function money(value: string | number) {
  const amount = Number(value);
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
  }).format(Number.isFinite(amount) ? amount : 0);
}

function date(value: Date | null | undefined) {
  if (!value) return "—";
  return new Intl.DateTimeFormat("en-GB", {
    timeZone: "Europe/London",
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).format(value);
}

function unitLabel(value: string) {
  if (value === "tonne") return "t";
  if (value === "load") return "load";
  return "job";
}

function wrap(text: string, maxChars: number) {
  const words = safeText(text).split(" ").filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxChars && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  }

  if (current) lines.push(current);
  return lines.length ? lines : ["—"];
}

function drawHeader(
  page: PDFPage,
  fonts: Fonts,
  title: string,
  reference: string,
  continuation = false,
) {
  const black = rgb(0.04, 0.04, 0.04);
  const orange = rgb(1, 0.39, 0.05);

  page.drawRectangle({
    x: 0,
    y: continuation ? 760 : 731,
    width: PAGE_WIDTH,
    height: continuation ? 82 : 111,
    color: black,
  });

  page.drawText("WASTE X", {
    x: MARGIN,
    y: continuation ? 814 : 806,
    size: 10,
    font: fonts.bold,
    color: orange,
  });

  page.drawText(continuation ? `${title} · CONTINUED` : title, {
    x: MARGIN,
    y: continuation ? 786 : 772,
    size: continuation ? 17 : 24,
    font: fonts.bold,
    color: rgb(1, 1, 1),
  });

  page.drawText(reference, {
    x: MARGIN,
    y: continuation ? 769 : 749,
    size: 9,
    font: fonts.regular,
    color: rgb(0.72, 0.72, 0.72),
  });
}

function drawTableHeader(page: PDFPage, fonts: Fonts, y: number) {
  const muted = rgb(0.45, 0.45, 0.45);

  page.drawRectangle({
    x: MARGIN,
    y: y - 4,
    width: PAGE_WIDTH - MARGIN * 2,
    height: 26,
    color: rgb(0.96, 0.94, 0.91),
  });

  page.drawText("DESCRIPTION", { x: MARGIN + 6, y: y + 5, size: 6.5, font: fonts.bold, color: muted });
  page.drawText("QTY", { x: 320, y: y + 5, size: 6.5, font: fonts.bold, color: muted });
  page.drawText("RATE", { x: 390, y: y + 5, size: 6.5, font: fonts.bold, color: muted });
  page.drawText("VAT", { x: 466, y: y + 5, size: 6.5, font: fonts.bold, color: muted });
  page.drawText("NET", { x: 520, y: y + 5, size: 6.5, font: fonts.bold, color: muted });

  return y - 27;
}

function drawFooter(page: PDFPage, fonts: Fonts, pageNumber: number, totalPages: number) {
  const muted = rgb(0.45, 0.45, 0.45);
  const lineColour = rgb(0.9, 0.88, 0.84);

  page.drawLine({
    start: { x: MARGIN, y: 42 },
    end: { x: PAGE_WIDTH - MARGIN, y: 42 },
    thickness: 1,
    color: lineColour,
  });

  page.drawText("Generated by Waste X from completed operational records", {
    x: MARGIN,
    y: 26,
    size: 7.5,
    font: fonts.regular,
    color: muted,
  });

  page.drawText(`Page ${pageNumber} of ${totalPages}`, {
    x: PAGE_WIDTH - MARGIN - 62,
    y: 26,
    size: 7.5,
    font: fonts.regular,
    color: muted,
  });
}

export async function buildCustomerInvoicePdf(document: InvoiceDocument) {
  const { invoice, lines } = document;
  const pdf = await PDFDocument.create();
  const fonts: Fonts = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
  };

  const black = rgb(0.04, 0.04, 0.04);
  const orange = rgb(1, 0.39, 0.05);
  const muted = rgb(0.45, 0.45, 0.45);
  const lineColour = rgb(0.9, 0.88, 0.84);

  const title = invoice.status === "draft" ? "DRAFT INVOICE" : "INVOICE";
  const reference = safeText(
    invoice.invoiceNumber ?? `DRAFT-${invoice.id.slice(0, 8).toUpperCase()}`,
  );

  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  drawHeader(page, fonts, title, reference);

  let y = 690;

  const drawBlock = (
    x: number,
    heading: string,
    values: Array<string | null | undefined>,
  ) => {
    page.drawText(heading.toUpperCase(), {
      x,
      y,
      size: 7,
      font: fonts.bold,
      color: orange,
    });

    let innerY = y - 16;
    for (const value of values.filter(Boolean)) {
      for (const row of wrap(value ?? "", 38).slice(0, 4)) {
        page.drawText(row, {
          x,
          y: innerY,
          size: 9,
          font: innerY === y - 16 ? fonts.bold : fonts.regular,
          color: black,
        });
        innerY -= 12;
      }
    }
  };

  drawBlock(MARGIN, "From", [
    invoice.supplierNameSnapshot,
    invoice.supplierAddressSnapshot,
    invoice.supplierCompanyNumber
      ? `Company No: ${invoice.supplierCompanyNumber}`
      : null,
    invoice.supplierVatNumber
      ? `VAT: ${invoice.supplierVatNumber}`
      : "VAT number not recorded",
  ]);

  drawBlock(310, "Bill to", [
    invoice.customerNameSnapshot,
    invoice.customerAddressSnapshot,
    invoice.customerEmailSnapshot,
  ]);

  page.drawLine({
    start: { x: MARGIN, y: 604 },
    end: { x: PAGE_WIDTH - MARGIN, y: 604 },
    thickness: 1,
    color: lineColour,
  });

  const meta = [
    ["Invoice date", date(invoice.issueDate)],
    ["Supply date", date(invoice.supplyDate)],
    ["Due date", date(invoice.dueDate)],
    ["Status", invoice.status.toUpperCase()],
  ];

  let metaX = MARGIN;
  for (const [label, value] of meta) {
    page.drawText(label.toUpperCase(), {
      x: metaX,
      y: 580,
      size: 6.5,
      font: fonts.bold,
      color: muted,
    });
    page.drawText(safeText(value), {
      x: metaX,
      y: 564,
      size: 9,
      font: fonts.bold,
      color: black,
    });
    metaX += 126;
  }

  y = drawTableHeader(page, fonts, 528);

  for (const invoiceLine of lines) {
    const descriptionLines = wrap(
      `${invoiceLine.jobNumberSnapshot ? `${invoiceLine.jobNumberSnapshot} · ` : ""}${invoiceLine.description}`,
      42,
    ).slice(0, 3);
    const rowHeight = Math.max(34, descriptionLines.length * 11 + 15);

    if (y - rowHeight < 90) {
      page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      drawHeader(page, fonts, title, reference, true);
      y = drawTableHeader(page, fonts, 725);
    }

    descriptionLines.forEach((row, index) => {
      page.drawText(row, {
        x: MARGIN + 6,
        y: y - 10 - index * 11,
        size: 8.5,
        font: index === 0 ? fonts.bold : fonts.regular,
        color: black,
      });
    });

    page.drawText(
      `${Number(invoiceLine.quantity).toFixed(invoiceLine.unit === "tonne" ? 3 : 0)} ${unitLabel(invoiceLine.unit)}`,
      { x: 320, y: y - 10, size: 8, font: fonts.regular, color: black },
    );
    page.drawText(money(invoiceLine.unitPrice), {
      x: 390,
      y: y - 10,
      size: 8,
      font: fonts.regular,
      color: black,
    });
    page.drawText(`${Number(invoiceLine.vatRate).toFixed(0)}%`, {
      x: 466,
      y: y - 10,
      size: 8,
      font: fonts.regular,
      color: black,
    });
    page.drawText(money(invoiceLine.netAmount), {
      x: 520,
      y: y - 10,
      size: 8,
      font: fonts.bold,
      color: black,
    });

    y -= rowHeight;
    page.drawLine({
      start: { x: MARGIN, y },
      end: { x: PAGE_WIDTH - MARGIN, y },
      thickness: 0.6,
      color: lineColour,
    });
    y -= 8;
  }

  if (y < 185) {
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    drawHeader(page, fonts, title, reference, true);
    y = 700;
  }

  const noteText = [invoice.notes, invoice.paymentInstructionsSnapshot]
    .filter(Boolean)
    .join(" · ");

  if (noteText) {
    page.drawText("NOTES / PAYMENT", {
      x: MARGIN,
      y: y - 8,
      size: 6.5,
      font: fonts.bold,
      color: muted,
    });

    wrap(noteText, 50)
      .slice(0, 5)
      .forEach((row, index) => {
        page.drawText(row, {
          x: MARGIN,
          y: y - 24 - index * 11,
          size: 8,
          font: fonts.regular,
          color: black,
        });
      });
  }

  const totalsY = y - 8;
  const totalsX = 370;
  const totalRows = [
    ["Net", money(invoice.subtotal)],
    ["VAT", money(invoice.vatTotal)],
    ["Total", money(invoice.total)],
  ];

  totalRows.forEach(([label, value], index) => {
    const rowY = totalsY - index * 24;
    page.drawText(label.toUpperCase(), {
      x: totalsX,
      y: rowY,
      size: index === 2 ? 9 : 7,
      font: fonts.bold,
      color: index === 2 ? orange : muted,
    });
    page.drawText(value, {
      x: 465,
      y: rowY,
      size: index === 2 ? 12 : 9,
      font: fonts.bold,
      color: black,
    });
  });

  const pages = pdf.getPages();
  pages.forEach((pdfPage, index) => {
    drawFooter(pdfPage, fonts, index + 1, pages.length);
  });

  return pdf.save();
}
