import Link from "next/link";

import { AdminEmptyState, AdminMetric, AdminPageHeader, AdminPanel, AdminStatusPill, TableCell, TableHead } from "@/components/admin/AdminUi";
import { requirePlatformAdmin } from "@/lib/access/require-platform-admin";
import { getAdminWorkflowHealth } from "@/modules/admin/core/getAdminWorkflowHealth";

export default async function AdminCommercialPage() {
  await requirePlatformAdmin();
  const data = await getAdminWorkflowHealth(90);
  const orgRows = data.organisations
    .filter((row) => row.commercial.completedJobs > 0 || row.customerInvoices.draft + row.customerInvoices.issued + row.customerInvoices.paid > 0)
    .sort((a, b) => b.commercial.unpricedCompletedJobs - a.commercial.unpricedCompletedJobs || b.commercial.invoiceReadyJobs - a.commercial.invoiceReadyJobs);

  return (
    <div className="space-y-7">
      <AdminPageHeader eyebrow="Product Operations" title="Commercial & Invoicing" description="Platform adoption and health for Job-specific commercial terms and customer operational invoices. These are invoices created by Waste X customers for their customers — not Waste X subscription billing." actions={<><Link href="/admin/billing" className="rounded-full border border-white/15 px-5 py-2.5 text-sm font-bold text-white hover:border-red-500">Platform Billing</Link><Link href="/admin/workflows" className="rounded-full bg-red-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-red-700">Workflow Health</Link></>} />

      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        <AdminMetric label="Completed Jobs" value={data.commercial.completedJobs} helper={`Current ${data.days}-day commercial window`} />
        <AdminMetric label="Priced" value={data.commercial.pricedCompletedJobs} helper="Completed Jobs with active revenue terms" />
        <AdminMetric label="Unpriced" value={data.commercial.unpricedCompletedJobs} helper="Completed Jobs missing confirmed revenue pricing" danger={data.commercial.unpricedCompletedJobs > 0} />
        <AdminMetric label="Invoice-ready" value={data.commercial.invoiceReadyJobs} helper="Priced completed Jobs not on an active invoice" />
        <AdminMetric label="Paid invoices" value={data.commercial.paidInvoices} helper={money(data.commercial.paidValue)} tone="success" />
      </section>

      <AdminPanel eyebrow="Organisation Health" title="Commercial workflow adoption" description="The Rate Library is not treated as the pricing authority here; this view checks active Job-specific revenue lines.">
        <div className="overflow-hidden rounded-2xl border border-black/10"><div className="overflow-x-auto"><table className="w-full min-w-[1250px] divide-y divide-black/10 text-sm"><thead><tr><TableHead>Organisation</TableHead><TableHead>Completed Jobs</TableHead><TableHead>Priced</TableHead><TableHead>Unpriced</TableHead><TableHead>Invoice-ready</TableHead><TableHead>Draft</TableHead><TableHead>Issued</TableHead><TableHead>Paid</TableHead></tr></thead><tbody className="divide-y divide-black/10">{orgRows.map((row) => <tr key={row.id} className="hover:bg-red-50/30"><TableCell><Link href={`/admin/organisations/${row.id}`} className="font-black text-black hover:text-red-600">{row.teamName}</Link></TableCell><TableCell>{row.commercial.completedJobs}</TableCell><TableCell>{row.commercial.pricedCompletedJobs}</TableCell><TableCell><span className={row.commercial.unpricedCompletedJobs > 0 ? "font-black text-red-600" : "font-black text-black"}>{row.commercial.unpricedCompletedJobs}</span></TableCell><TableCell>{row.commercial.invoiceReadyJobs}</TableCell><TableCell>{row.customerInvoices.draft}</TableCell><TableCell>{row.customerInvoices.issued}</TableCell><TableCell>{row.customerInvoices.paid}</TableCell></tr>)}</tbody></table></div></div>
      </AdminPanel>

      <AdminPanel eyebrow="Customer Invoice Register" title="Recent operational invoices" description="Read-only platform support view of invoices generated by customer organisations.">
        {data.recentCustomerInvoices.length === 0 ? <AdminEmptyState>No customer operational invoices were created in this reporting window.</AdminEmptyState> : <div className="overflow-hidden rounded-2xl border border-black/10"><div className="overflow-x-auto"><table className="w-full min-w-[1150px] divide-y divide-black/10 text-sm"><thead><tr><TableHead>Invoice</TableHead><TableHead>Organisation</TableHead><TableHead>Customer</TableHead><TableHead>Status</TableHead><TableHead>Total</TableHead><TableHead>Issued</TableHead><TableHead>Due</TableHead></tr></thead><tbody className="divide-y divide-black/10">{data.recentCustomerInvoices.map((invoice) => <tr key={invoice.id} className="hover:bg-red-50/30"><TableCell><span className="font-black text-black">{invoice.invoiceNumber ?? "Draft"}</span></TableCell><TableCell><Link href={`/admin/organisations/${invoice.organisationId}`} className="font-black text-black hover:text-red-600">{invoice.organisationName}</Link></TableCell><TableCell>{invoice.customerName}</TableCell><TableCell><AdminStatusPill label={invoice.status} tone={invoice.status === "paid" ? "success" : invoice.status === "issued" ? "dark" : invoice.status === "void" ? "danger" : "warning"} /></TableCell><TableCell>{money(invoice.total)}</TableCell><TableCell>{date(invoice.issueDate)}</TableCell><TableCell>{date(invoice.dueDate)}</TableCell></tr>)}</tbody></table></div></div>}
      </AdminPanel>
    </div>
  );
}

function money(value: number) { return new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP" }).format(value); }
function date(value: Date | string | null | undefined) { if (!value) return "—"; return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium" }).format(new Date(value)); }
