import Link from "next/link";

import {
  getReportFormatMeta,
  getReportTypeMeta,
  type ReportFormat,
  type ReportType,
} from "../core/reportTypes";
import ReportStatusBadge from "./ReportStatusBadge";

export type ReportHistoryItem = {
  id: string;
  organisationId?: string | null;
  organisationName?: string | null;
  requestedByUserId?: string | null;
  requestedByName?: string | null;
  requestedByEmail?: string | null;
  title: string;
  reportType: string;
  format: string;
  status: string;
  rowCount?: number | null;
  createdAt?: Date | string | null;
  generatedAt?: Date | string | null;
  downloadedAt?: Date | string | null;
  errorMessage?: string | null;
};

type ReportHistoryTableProps = {
  reports: ReportHistoryItem[];
  showOrganisation?: boolean;
  showRequestedBy?: boolean;
};

export default function ReportHistoryTable({
  reports,
  showOrganisation = false,
  showRequestedBy = true,
}: ReportHistoryTableProps) {
  if (!reports.length) {
    return (
      <div className="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center">
        <p className="text-sm font-semibold text-slate-900">
          No reports generated yet.
        </p>

        <p className="mt-2 text-sm text-slate-500">
          Generated reports will appear here with their audit trail.
        </p>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-slate-200 text-sm">
          <thead className="bg-slate-50 text-left text-xs uppercase tracking-[0.18em] text-slate-500">
            <tr>
              <th className="px-5 py-4">Report</th>
              {showOrganisation && <th className="px-5 py-4">Organisation</th>}
              {showRequestedBy && <th className="px-5 py-4">Generated By</th>}
              <th className="px-5 py-4">Format</th>
              <th className="px-5 py-4">Rows</th>
              <th className="px-5 py-4">Status</th>
              <th className="px-5 py-4">Created</th>
              <th className="px-5 py-4">Downloaded</th>
              <th className="px-5 py-4 text-right">Action</th>
            </tr>
          </thead>

          <tbody className="divide-y divide-slate-100">
            {reports.map((report) => {
              const reportTypeMeta = getReportTypeMeta(
                report.reportType as ReportType,
              );

              const formatMeta = getReportFormatMeta(
                report.format as ReportFormat,
              );

              return (
                <tr key={report.id} className="align-top">
                  <td className="px-5 py-4">
                    <div className="font-semibold text-slate-950">
                      {report.title}
                    </div>

                    <div className="mt-1 text-xs text-slate-500">
                      {reportTypeMeta?.label ?? report.reportType}
                    </div>

                    {report.errorMessage && (
                      <div className="mt-2 max-w-xs rounded-xl border border-red-100 bg-red-50 px-3 py-2 text-xs text-red-700">
                        {report.errorMessage}
                      </div>
                    )}
                  </td>

                  {showOrganisation && (
                    <td className="px-5 py-4 text-slate-700">
                      {report.organisationName ?? report.organisationId ?? "—"}
                    </td>
                  )}

                  {showRequestedBy && (
                    <td className="px-5 py-4">
                      <div className="text-slate-800">
                        {report.requestedByName ?? "Unknown user"}
                      </div>

                      {report.requestedByEmail && (
                        <div className="mt-1 text-xs text-slate-500">
                          {report.requestedByEmail}
                        </div>
                      )}
                    </td>
                  )}

                  <td className="px-5 py-4 text-slate-700">
                    {formatMeta?.label ?? report.format.toUpperCase()}
                  </td>

                  <td className="px-5 py-4 text-slate-700">
                    {report.rowCount ?? 0}
                  </td>

                  <td className="px-5 py-4">
                    <ReportStatusBadge status={report.status} />
                  </td>

                  <td className="px-5 py-4 text-slate-600">
                    {formatDate(report.createdAt)}
                  </td>

                  <td className="px-5 py-4 text-slate-600">
                    {formatDate(report.downloadedAt)}
                  </td>

                  <td className="px-5 py-4 text-right">
                    {report.status === "completed" ? (
                      <Link
                        href={`/api/reports/${report.id}/download`}
                        className="inline-flex rounded-2xl bg-black px-4 py-2 text-xs font-semibold text-orange-400 transition hover:bg-orange-500 hover:text-black"
                      >
                        Download
                      </Link>
                    ) : (
                      <span className="text-xs text-slate-400">
                        Unavailable
                      </span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function formatDate(value: Date | string | null | undefined) {
  if (!value) return "—";

  const date = value instanceof Date ? value : new Date(value);

  if (Number.isNaN(date.getTime())) return "—";

  return new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(date);
}