import { desc, eq, and } from "drizzle-orm";
import { redirect } from "next/navigation";

import { auth } from "@/auth";
import { database } from "@/db/database";
import { reportExports } from "@/db/schema";
import ReportGeneratorForm from "@/modules/reports/components/ReportGeneratorForm";
import ReportHistoryTable from "@/modules/reports/components/ReportHistoryTable";
import {
  canGenerateReport,
  canViewOrganisationReports,
  getReportUserContextFromSession,
} from "@/modules/reports/core/reportPermissions";
import { REPORT_TYPES } from "@/modules/reports/core/reportTypes";

export default async function OrganisationReportsPage() {
  const session = await auth();
  const context = getReportUserContextFromSession(session);

  if (!context.userId) {
    redirect("/login");
  }

  if (!context.organisationId) {
    redirect("/home");
  }

  if (!canViewOrganisationReports(context)) {
    redirect("/home");
  }

 const reports = await database
  .select()
  .from(reportExports)
  .where(
    and(
      eq(reportExports.organisationId, context.organisationId),
      eq(reportExports.status, "completed"),
    ),
  )
  .orderBy(desc(reportExports.createdAt))
  .limit(50);

  const allowedReportTypes = REPORT_TYPES.filter((report) =>
    canGenerateReport({
      context,
      reportType: report.value,
    }),
  ).map((report) => report.value);

  const totalReports = reports.length;
  const completedReports = reports.filter(
    (report) => report.status === "completed",
  ).length;
  const failedReports = reports.filter(
    (report) => report.status === "failed",
  ).length;
  const downloadedReports = reports.filter(
    (report) => Boolean(report.downloadedAt),
  ).length;

  return (
    <main className="min-h-screen bg-[#f7f3ed] text-black">
      <div className="ml-[20vw] min-h-screen px-8 pb-12 pt-[calc(13vh+2rem)]">
        <div className="mx-auto max-w-7xl space-y-8">
          {/* ================= HEADER ================= */}
          <section className="overflow-hidden rounded-[2rem] border border-black/10 bg-black shadow-sm">
            <div className="relative p-8 sm:p-10">
              <div className="absolute right-0 top-0 h-40 w-40 rounded-bl-full bg-orange-500/20" />
              <div className="absolute bottom-0 right-16 h-20 w-20 rounded-t-full bg-orange-400/10" />

              <div className="relative">
                <p className="text-xs font-black uppercase tracking-[0.32em] text-orange-400">
                  Waste X Reports
                </p>

                <div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
                  <div>
                    <h1 className="text-3xl font-black tracking-tight text-white sm:text-5xl">
                      Reports Centre
                    </h1>

                    <p className="mt-4 max-w-3xl text-sm leading-6 text-white/65">
                      Generate audit-ready exports for assignments, incidents,
                      receipts, Digital Waste Tracking submissions, listings and
                      user access records.
                    </p>
                  </div>

                  <div className="rounded-2xl border border-orange-400/20 bg-orange-500/10 px-5 py-4">
                    <p className="text-[10px] font-black uppercase tracking-[0.24em] text-orange-300/80">
                      Audit mode
                    </p>
                    <p className="mt-1 text-sm font-semibold text-white">
                      Every export is logged
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          {/* ================= SUMMARY CARDS ================= */}
          <section className="grid gap-4 md:grid-cols-4">
            <ReportMetricCard
              label="Total reports"
              value={totalReports}
              helper="Generated by your organisation"
            />

            <ReportMetricCard
              label="Completed"
              value={completedReports}
              helper="Ready for download"
            />

            <ReportMetricCard
              label="Downloaded"
              value={downloadedReports}
              helper="Exported for records"
            />

            <ReportMetricCard
              label="Failed"
              value={failedReports}
              helper="Needs review"
              danger={failedReports > 0}
            />
          </section>

          {/* ================= GENERATOR ================= */}
          <section className="rounded-[2rem] border border-black/10 bg-white/70 p-2 shadow-sm backdrop-blur">
            <div className="rounded-[1.5rem] border border-black/5 bg-white">
              {allowedReportTypes.length > 0 ? (
                <ReportGeneratorForm allowedReportTypes={allowedReportTypes} />
              ) : (
                <div className="p-8">
                  <p className="text-xs font-black uppercase tracking-[0.25em] text-orange-600">
                    Reports Centre
                  </p>

                  <h2 className="mt-3 text-2xl font-black tracking-tight text-black">
                    No report access available
                  </h2>

                  <p className="mt-2 max-w-2xl text-sm leading-6 text-black/55">
                    Your current role or active department does not have
                    permission to generate reports.
                  </p>
                </div>
              )}
            </div>
          </section>

          {/* ================= HISTORY ================= */}
          <section className="space-y-4">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <p className="text-xs font-black uppercase tracking-[0.25em] text-black/35">
                  Export history
                </p>

                <h2 className="mt-2 text-2xl font-black tracking-tight text-black">
                  Recent reports
                </h2>

                <p className="mt-1 max-w-2xl text-sm text-black/55">
                  These reports belong to your organisation and are tracked for
                  audit purposes.
                </p>
              </div>

              <div className="rounded-2xl border border-black/10 bg-white px-4 py-3 text-xs font-semibold text-black/50">
                Latest 50 exports
              </div>
            </div>

            <div className="rounded-[2rem] border border-black/10 bg-white/70 p-2 shadow-sm backdrop-blur">
              <ReportHistoryTable
                reports={reports}
                showOrganisation={false}
                showRequestedBy={false}
              />
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}

function ReportMetricCard({
  label,
  value,
  helper,
  danger = false,
}: {
  label: string;
  value: number;
  helper: string;
  danger?: boolean;
}) {
  return (
    <div className="rounded-[1.5rem] border border-black/10 bg-white p-5 shadow-sm">
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-[10px] font-black uppercase tracking-[0.22em] text-black/35">
            {label}
          </p>

          <p className="mt-3 text-3xl font-black tracking-tight text-black">
            {value}
          </p>
        </div>

        <span
          className={`mt-1 h-3 w-3 rounded-full ${
            danger ? "bg-red-500" : "bg-orange-500"
          }`}
        />
      </div>

      <p className="mt-3 text-xs font-medium leading-5 text-black/45">
        {helper}
      </p>
    </div>
  );
}